### PR TITLE
Add rubocop task, fix a bunch of style nits

### PR DESCRIPTION
**Pull request by llimllib**
Fix a bunch of style errors due to rubocop; for more info check out https://github.com/bbatsov/ruby-style-guide

There are still a bunch of rubocop errors, but this commit satisfies many of the "convention" level errors; I haven't even gotten into the lints yet.

*RFC*: do we want to satisfy rubocop? In general, I'm a big fan of static checking.

### CODE REVIEW

**Comment by harrisj** [comment]
I think the Rubocop maintainers argue that you should fix style errors only if you are working on new code, as going back to old code means a lot of time wasted and possible bugs. I know that this what Hound CI only flags for instance.

**Comment by alex** [comment]
Rubocop is clearly a lot stricter than I think is reasonable, and has some design choices that I disagree with, but I _love_ things like `go fmt`, so I'm all in.

**Comment by harrisj** [comment]
I found myself annoyed with how strict it was with some rules like line length (look, sometimes I want to go over 80 columns, that's my right as an American). So, I found myself disabling some rules when we tried it on MyUSA. Here is [the MyUSA .rubocop.yml file if it helps](https://github.com/18F/myusa/blob/devel/.rubocop.yml)

[Hound](https://houndci.com/) is a free-for-open-source CI that just runs Rubocop on branches to give them a stylistic comment. This sounds good in theory, but sometimes it means that a hotfix will generate 20+ comments from Hound which becomes 20+ emails sent from Github. You might decide it is helpful. I must admit that I personally found it more annoying than helpful.

**Comment by llimllib** [comment]
I particularly thought that changing `raise` to `fail` is pretty crazy, I had no idea `fail` was even a thing. The best change was, I thought, `is_multipart` to `multipart?`.

I would particularly love to use it like `go fmt`, enabling us to not fight at all about formatting.

Why does hound send multiple emails instead of just one? That seems like a poor decision.

**Comment by alex** [comment]
FWIW, I'd rather just get the codebase correct (it's small enough that we
can do it quickly) and then put the cheker in travis

On Mon, Aug 24, 2015 at 10:55 AM, Bill Mill <notifications@github.com>
wrote:

> I particularly thought that changing raise to fail is pretty crazy, I had
> no idea fail was even a thing. The best change was, I thought,
> is_multipart to multipart?.
>
> I would particularly love to use it like go fmt, enabling us to not fight
> at all about formatting.
>
> Why does hound send multiple emails instead of just one? That seems like a
> poor decision.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/connect_vbms/pull/19#issuecomment-134233157>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by harrisj** [comment]
Hound doesn't send emails. It just [makes comments on pull requests like this](https://github.com/18F/myusa/pull/713). The problem is that most of us have configured Github to send us emails for comments on Pull Requests, so it means a cascade of Hound emails.

**Comment by llimllib** [comment]
well I know that github sends emails, I'm just surprised hound doesn't add one comment to the PR with its findings instead of commenting 20 different times

**Comment by llimllib** [comment]
@alex that would be my preference as well

**Comment by amoose** [comment]
> I'd rather just get the codebase correct (it's small enough that we
> can do it quickly) and then put the cheker in travis

I would prefer this ^ approach to that noisy Hound :dog2:

**Comment by amoose** [comment]
Great start, @llimllib. I have rebased and will push up a new PR with no Rubocop failures. Stay tuned! :tv:

**Pull request closed without merging**
