### PR TITLE
Remove WSSE logging

### PR DESCRIPTION
**Pull request by harrisj**
Disable the logging by the do_wsse.sh script since it was filling up /tmp on production servers.

Fixes issue #101

### CODE REVIEW

**Comment by llimllib** [comment]
Are you sure that log4j doesn't put any logging anywhere? that piece of software is a mystery to me.

**Comment by alex** [comment]
Specifically (I guess), what's the intersection between this and `lib/log4j.properties`?

**Comment by llimllib** [comment]
I *think* the properties file is ignored right now? But this is all software by convention and I don't know the conventions.

**Comment by alex** [comment]
@plusjeff suggests we should change line one here https://github.com/department-of-veterans-affairs/connect_vbms/blob/master/lib/log4j.properties#L1 to `s/DEBUG/ERROR/`

**Comment by alex** [comment]
(Assuming that file is used)

**Comment by harrisj** [comment]
I have applied the suggestion from #104 and explicitly set the logging destination to two files named within the `do_wsse` script (as opposed to being passed in tempfiles from outside). This will still create two empty logfiles in /tmp, but it's better than what happened before while still allowing for logging

**Comment by harrisj** [comment]
Is there any point to this PR if the plan is to go with PR #106 instead?

**Comment by harrisj** [comment]
Closed because PR #106 was merged instead

**Pull request closed without merging**
