### PR TITLE
Fixed received dates error where all dates were the same

### PR DESCRIPTION
**Pull request by plusjeff**
Fixes issue #16 

@alex, @llimllib, or @amoose  - Ready for review

### CODE REVIEW

**Comment by llimllib** [comment]
Needs tests

**Comment by alex** [comment]
Yes, this would be a great chance to start writing some unit tests, where
we pass some pre-constructed XML to the `handle_response` method.

On Sat, Aug 22, 2015 at 2:56 PM, Bill Mill <notifications@github.com> wrote:

> Needs tests
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/connect_vbms/pull/18#issuecomment-133740024>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by llimllib** [comment]
Here's a start at some tests:

```
require 'spec_helper'

describe VBMS::Requests::ListDocuments do
  subject { VBMS::Requests::ListDocuments.new("123456788") }

  describe "#handle_response" do
    let(:res) { subject.handle_response(Nokogiri::XML(File.read("spec/responses/list_documents.rb"))) }

    it "returns the correct number of results" do
      expect(res.count).to eq 141
    end

    it "properly handles times" do
      expect(res[0].received_at).to eq Time.parse("2015-05-06-04:00").to_date
      expect(res[1].received_at).to eq Time.parse("2014-11-13-05:00").to_date
    end
  end
end
```

where spec/responses/list_documents.rb is a fixture containing [this document](https://gist.github.com/llimllib/8ebf907b0cf620f9feca)

**Comment by llimllib** [comment]
Also, the indentation should to be 2 spaces, not 4, and I think we probably should try to keep the style consistent to the other handle_response handlers, with a `map`?

We should probably set up rubocop formatting our code for us, I suppose, so we don't have to worry about it.

**Comment by plusjeff** [comment]
@llimllib Thanks for the comments (sadly, saw them after I wrote some tests). To explain the fix, the issue seemed like the use of `map`. `at_xpath` was choking inside the `map` call and was always getting called on the same node. Open to suggestion on how to fix it with a different xpath string, but I wasn't able to get it working using the same style of call.

**Comment by plusjeff** [comment]
@llimllib @alex Tests added, ready for re-review (P.S. Appreciate the feedback, Ruby/RSpec I'm definitely in newbie/intermediate turf.

**Comment by llimllib** [comment]
Here's one way you could fix it while maintaining the map:

```ruby
        doc.xpath(
          "//v4:listDocumentsResponse/v4:result", VBMS::XML_NAMESPACES
        ).map do |el|
          received_dt = el.at_xpath(
            "ns2:receivedDt/text()", VBMS::XML_NAMESPACES
          )
          VBMS::Document.new(
            el["id"],
            el["filename"],
            el["docType"],
            el["source"],
            received_dt.nil? ? nil : Time.parse(received_dt.content).to_date
          )
        end
```

I'd also like to put the ListDocuments tests into a new spec file

**Comment by alex** [comment]
If I'm following Bill, the change here is to remove the `//` from the 2nd
xpath?

On Sun, Aug 23, 2015 at 9:31 AM, Bill Mill <notifications@github.com> wrote:

> Here's one way you could fix it while maintaining the map:
>
>         doc.xpath(
>           "//v4:listDocumentsResponse/v4:result", VBMS::XML_NAMESPACES
>         ).map do |el|
>           received_dt = el.at_xpath(
>             "ns2:receivedDt/text()", VBMS::XML_NAMESPACES
>           )
>           VBMS::Document.new(
>             el["id"],
>             el["filename"],
>             el["docType"],
>             el["source"],
>             received_dt.nil? ? nil : Time.parse(received_dt.content).to_date
>           )
>         end
>
> I'd also like to put the ListDocuments tests into a new spec file
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/connect_vbms/pull/18#issuecomment-133832821>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by llimllib** [comment]
yes, exactly, and you also need to check `received_dt` for nil

**Comment by alex** [comment]
I still don't understand why that's the case, but SGTM.

On Sun, Aug 23, 2015 at 9:42 AM, Bill Mill <notifications@github.com> wrote:

> yes, exactly, and you also need to check received_dt for nil
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/connect_vbms/pull/18#issuecomment-133838742>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by llimllib** [comment]
// searches for all elements in the document starting at the root. From the spec:

//para selects all the para descendants of the document root and thus selects all para elements in the same document as the context node



.// would work for us as well, I believe

**Comment by plusjeff** [comment]
@llimllib @alex All set. Ready for re-review.

**Comment by llimllib** [comment]
LGTM

**Pull request merged**
