### PR TITLE
[Issue #65] Updates test keystore fixtures

### PR DESCRIPTION
**Pull request by amoose**
```
➜  connect_vbms git:(fix/new_keystore) ✗ keytool -list -v -keystore spec/fixtures/test_keystore.jks
Enter keystore password:

Keystore type: JKS
Keystore provider: SUN

Your keystore contains 3 entries

Alias name: vbms_server_key
Creation date: Sep 15, 2015
Entry type: PrivateKeyEntry
Certificate chain length: 1
Certificate[1]:
Owner: CN=test.vbms.va.gov, O=USDS, L=DC, ST=Washington, C=US
Issuer: CN=test.vbms.va.gov, O=USDS, L=DC, ST=Washington, C=US
Serial number: 85b79acec43ed30a
Valid from: Tue Sep 15 11:29:35 PDT 2015 until: Wed Sep 14 11:29:35 PDT 2016
Certificate fingerprints:
	 MD5:  2F:41:FA:C8:23:72:04:7C:C2:3A:1F:4B:78:4F:BA:CD
	 SHA1: 7B:EB:91:0D:20:C1:9A:BC:90:BE:30:A8:B5:CF:89:4C:1D:CA:F8:F4
	 Signature algorithm name: SHA256withRSA
	 Version: 3

Extensions:

#1: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: 6B 97 69 4B AC 1A F1 FA   AA 5A CB AF 8A B2 BC F6  k.iK.....Z......
0010: C5 73 A3 90                                        .s..
]
]

#2: ObjectId: 2.5.29.19 Criticality=false
BasicConstraints:[
  CA:true
  PathLen:2147483647
]

#3: ObjectId: 2.5.29.35 Criticality=false
AuthorityKeyIdentifier [
KeyIdentifier [
0000: 6B 97 69 4B AC 1A F1 FA   AA 5A CB AF 8A B2 BC F6  k.iK.....Z......
0010: C5 73 A3 90                                        .s..
]

]



*******************************************
*******************************************


Alias name: vbms_server_cert
Creation date: Sep 15, 2015
Entry type: trustedCertEntry

Owner: CN=test.vbms.va.gov, O=USDS, L=DC, ST=Washington, C=US
Issuer: CN=test.vbms.va.gov, O=USDS, L=DC, ST=Washington, C=US
Serial number: 85b79acec43ed30a
Valid from: Tue Sep 15 11:29:35 PDT 2015 until: Wed Sep 14 11:29:35 PDT 2016
Certificate fingerprints:
	 MD5:  2F:41:FA:C8:23:72:04:7C:C2:3A:1F:4B:78:4F:BA:CD
	 SHA1: 7B:EB:91:0D:20:C1:9A:BC:90:BE:30:A8:B5:CF:89:4C:1D:CA:F8:F4
	 Signature algorithm name: SHA256withRSA
	 Version: 3

Extensions:

#1: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: 6B 97 69 4B AC 1A F1 FA   AA 5A CB AF 8A B2 BC F6  k.iK.....Z......
0010: C5 73 A3 90                                        .s..
]
]

#2: ObjectId: 2.5.29.19 Criticality=false
BasicConstraints:[
  CA:true
  PathLen:2147483647
]

#3: ObjectId: 2.5.29.35 Criticality=false
AuthorityKeyIdentifier [
KeyIdentifier [
0000: 6B 97 69 4B AC 1A F1 FA   AA 5A CB AF 8A B2 BC F6  k.iK.....Z......
0010: C5 73 A3 90                                        .s..
]

]



*******************************************
*******************************************


Alias name: importkey
Creation date: Sep 15, 2015
Entry type: PrivateKeyEntry
Certificate chain length: 1
Certificate[1]:
Owner: CN=test.vbms.va.gov, O=USDS, L=DC, ST=Washington, C=US
Issuer: CN=test.vbms.va.gov, O=USDS, L=DC, ST=Washington, C=US
Serial number: 999e6fa57dae3af4
Valid from: Tue Sep 15 11:29:35 PDT 2015 until: Wed Sep 14 11:29:35 PDT 2016
Certificate fingerprints:
	 MD5:  CD:C3:E5:54:78:44:A8:4B:5E:69:E0:C4:FE:26:20:0E
	 SHA1: D9:D7:05:1D:BE:F8:6D:F9:D5:21:BA:0D:38:CE:99:A1:3F:1F:24:81
	 Signature algorithm name: SHA256withRSA
	 Version: 1


*******************************************
*******************************************


```

This was generated from a script. I will post a PR for the script shortly.

### CODE REVIEW

**Comment by llimllib** [comment]
Add the script to generate these!

**Comment by amoose** [comment]
Stay tuned! :tv:

**Comment by harrisj** [comment]
LGTM. I think the plan by @amoose is to make the script to generate a separate WIPPR, so we can quickly merge this one to rebase other PRs against.

**Comment by llimllib** [comment]
LGTM, confirmed to work for me, and thanks!

**Pull request merged**
