### PR TITLE
[Issue #67] Adds script and doc for generating keystore

### PR DESCRIPTION
**Pull request by amoose**
It's not pretty, but it works. This script will need to be run once per year, and is compatible with our pending ruby encryption code.

### CODE REVIEW

**Comment by harrisj** [comment]
Looks good to me

**Comment by amoose** [comment]
@llimllib Do you mind testing this out when you have a sec? [included documentation](https://github.com/department-of-veterans-affairs/connect_vbms/blob/feature/keystore_script/docs/generating_new_keystore.rst)

**Comment by llimllib** [comment]
LGTM. The documentation should probably go in the docs, not the wiki though?

**Comment by amoose** [comment]
docs/generating_new_keystore.rst looks like a wiki thanks to :octocat:

**Comment by llimllib** [comment]
doh! Rock and roll :ship: :it:

**Pull request merged**
