### PR TITLE
Fixes #14 -- always use httpclient isntead of httpi

### LINKED ISSUE #14: Leverage approriate client to avoid unnecessary handshakes when making repeat HTTP requests
Issue:

When making multiple HTTP requests to the same host, we want to avoid new TCP connections and TLS handshakes for subsequent requests.

> Is `HTTPI` the best HTTP lib to use if I want to make many requests to the same host?
> The way it's API is structured leads me to believe that htat means a new TCP conncetion, a new TLS session, for each request.
> Which would be cruddy.
> Is there an HTTP API which is good?

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
I don't think this is complete, @harrisj if you could take a look I'd appreciate it, there's more code for processing responses than I remember.

**Comment by alex** [comment]
Looks like there's a bunch of tests that need to be updated.

**Comment by harrisj** [comment]
Okay. I will pick it up. Thanks!

**Comment by alex** [comment]
Thank you! :sparkles:

On Wed, Nov 4, 2015 at 6:01 PM, Jacob Harris <notifications@github.com>
wrote:

> Okay. I will pick it up. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/connect_vbms/pull/99#issuecomment-153897396>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by harrisj** [comment]
All tests with webmocks now pass, but several fail when connecting directly to VBMS. **Do not merge yet.**

**Comment by amoose** [comment]
This looks good to me! These changes all appear to be internal-only and removes a depenency; :ship:  
Can we get a real-world test by @alex or @llimllib ?

**Comment by alex** [comment]
I can confirm with the preprod environment tomorrow morning.

On Mon, Nov 9, 2015 at 6:44 PM, Amos Stone <notifications@github.com> wrote:

> This looks good to me! These changes all appear to be internal-only and
> removes a depenency; [image: :ship:]
>
> Can we get a real-world test by @alex <https://github.com/alex> or
> @llimllib <https://github.com/llimllib> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/connect_vbms/pull/99#issuecomment-155235132>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by harrisj** [comment]
I took the liberty of bumping up the gem version just in case

**Comment by alex** [comment]
Confirmed that this works in all of our envs. Nice work everybody, merging!

**Pull request merged**
