### PR TITLE
Adds Vagrantfile and bootstrap script

### PR DESCRIPTION
**Pull request by amoose**
Adds Vagrant VM support for both VirtualBox and VMWare Fusion
Bootstraps new VM with application dependencies

### CODE REVIEW

**Comment by llimllib** [comment]
I'll test and review it if you'll add instructions for somebody that has Virtualbox and vagrant installed, but no more than a passing understanding of how those two things work

**Comment by amoose** [comment]
Thanks! It's as easy as:

Copy the provided example Vagrantfile and Vagrant up!
```
$ cp Vagrantfile.example Vagrantfile
$ vagrant up
```

**Comment by amoose** [comment]
VM development workflow:

  - 1. Check VM status.
```bash
$ vagrant status
Current machine states:

default                   saved (virtualbox)

To resume this VM, simply run `vagrant up`.
```

  - 2. Launch Vagrant VM
```bash
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
...
==> default: Machine booted and ready!
```

  - 3. Log in to VM and run specs
```bash
$ vagrant ssh
Welcome to Ubuntu 12.04.5 LTS (GNU/Linux 3.2.0-88-virtual x86_64)
...
vagrant@connect-vbms-dev-box:~$ cd /vagrant/connect_vbms
vagrant@connect-vbms-dev-box:/vagrant/connect_vbms$ bundle exec rspec
```

  - 4. When done, exit and suspend VM.
```bash
vagrant@connect-vbms-dev-box:/vagrant/connect_vbms$ exit
Connection to 127.0.0.1 closed.
$ vagrant suspend
==> default: Saving VM state and suspending execution...
```

**Comment by amoose** [comment]
I updated the bootstrap script yesterday. If you have any issues use:
```bash
$ vagrant destroy # WARNING!!! ALL IS LOST
```
to destroy the VM. and `vagrant up` to have it rebuilt.

**Comment by llimllib** [comment]
did you push your changes? I'm on https://github.com/18F/connect_vbms/commit/0da85144c5073c8a3532c157b66c1f00ce9043ae, but that's four days old and appears to be the most recent commit

**Comment by amoose** [comment]
That is the correct revision. I did push up the changes, but rebased :postal_horn: and squashed minor commit on top of last commit for brevity.

**Comment by llimllib** [comment]
I get a bunch of:

```
==> default: ruby-2.1.2 is not installed.
==> default: To install do: 'rvm install ruby-2.1.2'
```

because we have a `.ruby-version` with 2.1.2.

**Comment by amoose** [comment]
That's your local .ruby-version causing RVM to bark. I included the `--auto-dotfiles` flag but it didn't seem to fix that.

**Comment by llimllib** [comment]
doop, can't believe I didn't notice that. LGTM

**Comment by amoose** [comment]
Moved help to wiki -> https://github.com/department-of-veterans-affairs/connect_vbms/wiki/Developing-with-Vagrant

**Pull request merged**
