### PR TITLE
[WIPPR] Remove mail gem

### PR DESCRIPTION
**Pull request by harrisj**
Fixes issue #55. Still not quite elegant yet

### CODE REVIEW

**Comment by amoose** [comment]
Is this ready for review?

**Comment by llimllib** [comment]
I don't really like bringing it into connect_vbms? Seems better to me to leave it in the mail gem?

**Comment by harrisj** [comment]
Okay, maybe I can engineer a different regexp. The whole point was to remove the inclusion of the Mail gem just for multipart processing

**Comment by llimllib** [comment]
I find it heavyweight too, but I prefer having it in a separate tested library rather than being our responsibility; if somebody were to find a bug in that regex it'd (hopefully) get fixed in the mail gem but we'd be very unlikely to notice it

**Comment by harrisj** [comment]
This pull request will **not** be merged as we decided to just preserve the dependency on the Mail gem for now.

**Pull request closed without merging**
