### PR TITLE
Add Simplecov code coverage reporting

### LINKED ISSUE #7: Get coverage numbers
I'm guessing they're not good, and we need the numbers to improve them.

### PR DESCRIPTION
**Pull request by llimllib**
Current stats: 270 / 311 LOC (86.82%) covered.

(Obviously this is a very shallow report)

Closes #7

### CODE REVIEW

**Comment by llimllib** [comment]
@amoose want to review this one as well?

**Comment by amoose** [comment]
:eyes:

**Comment by amoose** [comment]
Tested! :+1: 

screen shot 2015-08-19 at 8 51 52 am

**Comment by amoose** [comment]
My coverage stats are lower because of my specs failing without credentials. 

We can also enable `refuse_coverage_drop` in our spec_helper to have Travis return :red_circle: if coverage drops. 

```
require 'simplecov'
SimpleCov.start do
  refuse_coverage_drop
end
```

**Comment by llimllib** [comment]
> My coverage stats are lower because of my specs failing without credentials.

Yeah, I wonder if we should exclude integration tests from coverage stats?

**Pull request closed without merging**
